// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsw7plwdh7MSIldhGLeDy5N9nI4JI8Qhg',
    appId: '1:527388829317:web:1173bdf4f26ed0be8e6bec',
    messagingSenderId: '527388829317',
    projectId: 'bharatconnect-92c74',
    authDomain: 'bharatconnect-92c74.firebaseapp.com',
    storageBucket: 'bharatconnect-92c74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeaepbZxuphvKOcccQvBxy_SemHd5eXQY',
    appId: '1:527388829317:android:3b06055a6487353f8e6bec',
    messagingSenderId: '527388829317',
    projectId: 'bharatconnect-92c74',
    storageBucket: 'bharatconnect-92c74.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsw7plwdh7MSIldhGLeDy5N9nI4JI8Qhg',
    appId: '1:527388829317:web:094ccca7cb1e2ff68e6bec',
    messagingSenderId: '527388829317',
    projectId: 'bharatconnect-92c74',
    authDomain: 'bharatconnect-92c74.firebaseapp.com',
    storageBucket: 'bharatconnect-92c74.firebasestorage.app',
  );
}
